---
- hosts: all
  gather_facts: false  
  tasks:
    - name: Create Labdroid Organization
      local_action: 
        module: foreman_organization
        username: "{{ satellite_login }}"
        password: "{{ satellite_password }}"
        server_url: "https://{{ inventory_hostname }}/api/v2"
        validate_certs: "{{ satellite_validate_certs }}"
        name: "Labdroid"
        description: "Anthony Green's Home Lab Organization"
        label: "labdroid"
        state: present

    - name: Get our manifest from S3 storage
      run_once: true
      local_action:
        module: aws_s3
        s3_url: "{{ s3_url }}"
        aws_access_key: "{{ minio_access_key }}"
        aws_secret_key: "{{ minio_secret_key }}"
        bucket: labdroid
        object: "{{ manifest_filename }}"
        dest: "/tmp/{{ manifest_filename }}"
        mode: get

    - name: Upload a Red Hat subscription manifest
      local_action:
        module: katello_manifest
        username: "{{ satellite_login }}"
        password: "{{ satellite_password }}"
        server_url: "https://{{ inventory_hostname }}"
        verify_ssl: "{{ satellite_validate_certs }}"
        organization: "Labdroid"
        state: present
        manifest_path: "/tmp/{{ manifest_filename }}"

    - name: Create Labdroid Lab Location
      local_action: 
        module: foreman_location
        username: "{{ satellite_login }}"
        password: "{{ satellite_password }}"
        server_url: "https://{{ inventory_hostname }}/api/v2"
        validate_certs: "{{ satellite_validate_certs }}"
        name: "Lab"
        organizations:
          - "Labdroid"
        state: present

    - name: Delete the Default Organization
      local_action: 
        module: foreman_organization
        username: "{{ satellite_login }}"
        password: "{{ satellite_password }}"
        server_url: "https://{{ inventory_hostname }}/api/v2"
        validate_certs: "{{ satellite_validate_certs }}"
        name: "Default Organization"
        state: absent

    # - name: Delete the Default Location
    #   local_action: 
    #     module: foreman_location
    #     username: "{{ satellite_login }}"
    #     password: "{{ satellite_password }}"
    #     server_url: "https://{{ inventory_hostname }}/api/v2"
    #     validate_certs: "{{ satellite_validate_certs }}"
    #     name: "Default Location"
    #     state: absent

    - name: "Enable/Disable katello repository set"
      vars:
        - repositories:
          - name: rhel-7-server-ansible-2.6-rpms
            arch: x86_64
          - name: rhel-7-server-extras-rpms
            arch: x86_64
          - name: rhel-7-server-optional-rpms
            arch: x86_64
            release: 7Server
          - name: rhel-7-server-rpms
            arch: x86_64
            release: 7Server
          - name: rhel-7-server-rh-common-rpms
            arch: x86_64
            release: 7Server
          - name: rhel-7-server-supplementary-rpms
            arch: x86_64
            release: 7Server
          - name: rhel-7-server-satellite-maintenance-6-rpms
            arch: x86_64
          - name: rhel-7-server-satellite-tools-6.5-rpms
            arch: x86_64
          - name: rhel-server-rhscl-7-rpms
            arch: x86_64
            release: 7Server
      local_action:
        module: katello_repository_set
        username: "{{ satellite_login }}"
        password: "{{ satellite_password }}"
        server_url: "https://{{ inventory_hostname }}/api/v2"
        validate_certs: "{{ satellite_validate_certs }}"
        organization: Labdroid
        label: "{{ item.name }}"
        repositories:
          - releasever: "{{ item.release | default (omit)}}"
            basearch: "{{ item.arch | default (omit)}}"
        state: enabled
        repositories: "{{ repositories }}"
        label: rhel-7-server-rpms
      loop: "{{ repos }}"
  
