---
- hosts: all
  gather_facts: false  
  tasks:
    - name: Create Labdroid Organization
      local_action: 
        module: foreman_organization
        username: "{{ satellite_login }}"
        password: "{{ satellite_password }}"
        server_url: "https://{{ inventory_hostname }}/api/v2"
        validate_certs: "{{ satellite_validate_certs }}"
        name: "Labdroid"
        description: "Anthony Green's Home Lab Organization"
        label: "labdroid"
        state: present

    - name: Get our manifest from S3 storage
      run_once: true
      local_action:
        module: aws_s3
        s3_url: "{{ s3_url }}"
        aws_access_key: "{{ minio_access_key }}"
        aws_secret_key: "{{ minio_secret_key }}"
        bucket: labdroid
        object: "{{ manifest_filename }}"
        dest: "/tmp/{{ manifest_filename }}"
        mode: get

    - name: Upload a Red Hat subscription manifest
      local_action:
        module: katello_manifest
        username: "{{ satellite_login }}"
        password: "{{ satellite_password }}"
        server_url: "https://{{ inventory_hostname }}"
        verify_ssl: "{{ satellite_validate_certs }}"
        organization: "Labdroid"
        state: present
        manifest_path: "/tmp/{{ manifest_filename }}"

    - name: Create Labdroid Lab Location
      local_action: 
        module: foreman_location
        username: "{{ satellite_login }}"
        password: "{{ satellite_password }}"
        server_url: "https://{{ inventory_hostname }}/api/v2"
        validate_certs: "{{ satellite_validate_certs }}"
        name: "Lab"
        organizations:
          - "Labdroid"
        state: present

    - name: Delete the Default Organization
      local_action: 
        module: foreman_organization
        username: "{{ satellite_login }}"
        password: "{{ satellite_password }}"
        server_url: "https://{{ inventory_hostname }}/api/v2"
        validate_certs: "{{ satellite_validate_certs }}"
        name: "Default Organization"
        state: absent

    - name: Delete the Default Location
      local_action: 
        module: foreman_location
        username: "{{ satellite_login }}"
        password: "{{ satellite_password }}"
        server_url: "https://{{ inventory_hostname }}/api/v2"
        validate_certs: "{{ satellite_validate_certs }}"
        name: "Default Location"
        state: absent

    - name: "Enable/Disable katello repository set"
      vars:
        - name: "Red Hat Enterprise Linux 7 Server (RPMs)"
        - organization: Labdroid
        - state: enabled
        - repositories:
            - releasever: "7.3"
              basearch: "x86_64"
      local_action:
        module: katello_repository_set
        username: "{{ satellite_login }}"
        password: "{{ satellite_password }}"
        server_url: "https://{{ inventory_hostname }}/api/v2"
        validate_certs: "{{ satellite_validate_certs }}"
        name: "Red Hat Enterprise Linux 7 Server (RPMs)"
        organization: Labdroid
        product: Red Hat Enterprise Linux Server
        state: enabled
        repositories: "{{ repositories }}"
        label: rhel-7-server-rpms
